# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_pb2 as data__pb2


class TransmitDataStub(object):
    """package grpc_test;

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoTransmit = channel.unary_unary(
                '/TransmitData/DoTransmit',
                request_serializer=data__pb2.DataRequest.SerializeToString,
                response_deserializer=data__pb2.DataResponse.FromString,
                )


class TransmitDataServicer(object):
    """package grpc_test;

    """

    def DoTransmit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransmitDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoTransmit': grpc.unary_unary_rpc_method_handler(
                    servicer.DoTransmit,
                    request_deserializer=data__pb2.DataRequest.FromString,
                    response_serializer=data__pb2.DataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TransmitData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransmitData(object):
    """package grpc_test;

    """

    @staticmethod
    def DoTransmit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TransmitData/DoTransmit',
            data__pb2.DataRequest.SerializeToString,
            data__pb2.DataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
